baseURL = "http://example.org/"
languageCode = "zh-CN"
title = "言白话的博客"
theme = "maupassant"
preserveTaxonomyNames = true
disablePathToLower = true

[author]
  name = "言白话"

[params]
  author = "言白话"
  subtitle = "专注于Java、python、移动互联网、项目管理、软件架构"
  keywords = "言白话,java,android,博客,项目管理,python,软件架构,公众号,小程序"
  description = "专注于IT互联网，包括但不限于Go语言(golang)、Java、Android、Python、项目管理、抖音分析、软件架构等"

[menu]
  [[menu.main]]
    identifier = "books"
    name = "资料"
    url = "/books/"
    weight = 2
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4	
	
[[params.links]]
  title = "Android Gradle权威指南"
  name = "Android Gradle权威指南"
  url = "http://yuedu.baidu.com/ebook/14a722970740be1e640e9a3e"
[[params.links]]
  title = "常用开发工具CDN镜像"
  name = "常用开发工具CDN镜像"
  url = "http://mirrors.flysnow.org/"	